:lang: ja
:doctype: book
:toc: left
:toc-title: 目次
:sectnums:
:sectlinks:
:icons: font
:source-highlighter: coderay
:exmaple-caption: 例
:table-caption: 表
:figure-caption: 図
:author: homuraction
:revnumber: 0.1
:revdate: 2018/08/20

= Hypertext Transfer Protocol (HTTP/1.1): Range Requests

== Abstract

HTTPは状態を持たないApplication層のプロトコルであり、それは配布用であり協力的でありhypertext informationシステムである.

== Introduction

HTTP clientはしばしばリクエストの中止や接続の切断によって生じるデータ転送割り込みに出くわす.
あるclientが一部の表現(おそらくリクエストデータの一部を指している)を保持していた時、表現全体を(再度)転送するよりも後続のリクエストにおいて残りの表現を要求する事の方が理想的である.
同様に、ローカルストレージが制限された端末にとって１ページの非常に巨大な文書や、埋め込まれた画像のような制限以上に大きな表現の部分集合のみをリクエストできる事は旨味がある.

この文書はHTTP/1.1 Range Request、部分レスポンスそしてmultipart/byteranges media typeを定義する.

Range requestsはHTTPのオプショナルな機能として設計されており、したがって、この機能を実装していない受信者(もしくは対象資源に対してこれをサポートしていないか)は相互運用性に衝撃を与えないように通常のGetリクエストとして応答する事ができる.
部分的なレスポンスはこの機能を実装していないであろうキャッシュにより完全なレスポンス応答であると誤解されない事が明確なステータスコードによって示される.

Range requestsメカニズムは拡張可能な範囲型を許すように設計されているものの、この仕様ではbyte範囲のためのリクエストのみを定義する.

=== Conformance and Error Handling

エラー処理に関する適合基準と考慮事項は https://tools.ietf.org/html/rfc7230#section-2.5[Section 2.5 of [RFC7230]] にて定義されている.

=== Syntax Notation

この仕様はABNF記法とそのリスト拡張を使用しており、それはabnf.adocおよびabnf-list-extension.adocにそれぞれ記述しているためそちらを参照する事.
付録Cでは他の文書から輸入された規則を説明する.
付録Dでは標準ABNF記法を全てのlist演算子で拡張した文法を集め紹介する.

== Range Units

ある表現は様々な構造単位に対応した部分範囲に分割する事ができ、それは表現のメディア型に固有の構造体に依存する.
この `range unit` はRange requestsに対応する事を喧伝するための `Accept-Ranges` レスポンスヘッダフィールド用いられ、`Range` リクエストヘッダフィールドはリクエストされる表現の一部を描くために用いられ、`Content-Range` ペイロードヘッダフィールドは転送されている表現のあるPartに関する範囲説明している.

```
  range-unit = bytes-unit / other-range-unit
      ; bytes-unit規則またはother-range-unit規則の
      ;   どちらかがrange-unitとして採用される
```

=== Byte Ranges

表現データがオクテット列としてペイロード内で転送される時、あるbyte範囲はHTTP上の任意の転送可能な表現に対する意味のある部分範囲である.
`bytes` range unitはオクテット列のデータの部分範囲を表現するために定義される.

```
  bytes-unit = "bytes"
      ; range-unitの具体的な値としての1つは
      ; range-unit = "bytes"
      ; であるという事
```

あるbyte-rangeリクエストは単一のbyte範囲、または、単一表現に収まる範囲集合を指定することができる.

```
  byte-ranges-specifier = bytes-unit "=" byte-range-set
  byte-range-set        = 1#( byte-range-spec /
                              suffix-byte-range-spec)
                              ; 1つ以上の
                              ; byte-range-specまたは
                              ; suffix-byte-range-specを
                              ; カンマ区切り(OWS有り)で並べたもの
  byte-range-spec       = first-byte-pos "-" [ last-byte-pos ]
                            ; last-byte-posはoptional
  first-byte-pos        = 1*DIGIT ; 1桁以上の10進数
  last-byte-pos         = 1*DIGIT
```

`byte-range-spec` 内の `first-byte-pos` 値には範囲内の最初のbyteからのオフセットを与える.
`last-byte-pos` 値には範囲内の最後のbyteからのオフセットを与える.
指定されたbyte位置は包括的なものである.
byteオフセットは0から始まる.

`byte-ranges-specifier` 値の例は下記である:

```
- 最初の500 bytes (byteオフセット 0-499, inclusive):
  byte-ranges-specifier           =
    bytes-unit "=" byte-range-set =
    "bytes" "=" first-byte-pos    =
    bytes=0-499
- 第二の500 bytes (byteオフセット500-999, inclusive):
  bytes=500-999
```

もし `last-byte-pos` 値が存在し、且つ、`first-byte-pos` よりも小さい場合、 `byte-range-spec` は無効である.

clientは選択された表現のサイズを知らずにリクエストされたbyte数を制限する事ができる.
もし `last-byte-pos` 値が存在しない、または、もしその値が現在の表現の長さ以上であるならば、そのbyte範囲は表現の残りの部分であると解釈される(serverは現在選択された表現の長さより1小さい値を `last-byte-pos` として置き換える).

あるclientは `suffix-byte-range-spec` を用いることで選択された表現の `最後からN bytes部分` をリクエストする事ができる.

```
  suffix-byte-range-spec = "-" suffix-length
  suffix-length          = 1*DIGIT
```

もし選択された表現が指定された `suffix-length` よりも短い場合、表現全体が用いられる.

追加例として、長さが10,000の表現を仮定すると:

```
- 最後の500 bytes (byteオフセット 9500-9999, inclusive):
  bytes=-500
または
  bytes=9500-
- 最初と最後のbytesのみ (bytes 0 と 9999):
  bytes=0-0,-1
- その他の有効だが正準ではない、第二の500 bytesの仕様 (bytesオフセット 500-999, inclusive)
  bytes=500-600,601-999
  bytes=500-700,601-999
```

`byte-range` 構文内において、`first-byte-pos` 、`last-byte-pos` 及び `suffix-length` はオクテットの10進数として表現される.
そこにはペイロードの長さに対する事前定義された制限が無いため、受信者は**潜在的に大きな10進数を予期せねばならない**し、**整数変換オーバーフローに対する解析エラーを防がなければならない**.

=== Other Range Units

Range unitsは拡張可能である事を意図している.
新たなRange unitsは、Section 5.1で定義するように、IANAに登録すべきである.

=== Accept-Ranges

`Accept-Ranges` ヘッダフィールドはserverが対象資源に対しRange requestsをサポートしている事を示させる.

```
  Accept-Ranges     = acceptable-ranges
  acceptable-ranges = 1#range-unit / "none"
                        ; bytes,other-range-unit,...
                        ; または
                        ; none
                        ; など
```

与えられた対象資源に対してbyte-range requestsをサポートするとあるオリジンserverがどのrange unitsがサポートされているのかを示すために `Accept-Ranges: bytes` を送信するかもしれない.

あるclientは関連資源に対するこのヘッダフィールドを受け取る事なくRange requestsを生成するかもしれない.
Ranges unitsはSection 2で定義されている.

対象資源に対して任意の種類のRange requestをサポートしないとあるserverはclientに対しRange requstを試みない事を知らせるために `Accept-Ranges: none` を送信するかもしれない.

== Range Requests

=== Range

GETリクエスト上の `Range` ヘッダフィールドはメソッドの意味を選択された表現データ全体よりも、1つ以上の部分範囲だけを転送するリクエストに変更する.

```
  Range                  = byte-ranges-specifier / other-ranges-specifier
  other-ranges-specifier = other-range-unit "=" other-range-set
  other-range-set        = 1*VCHAR
```

あるserverはRangeヘッダフィールドを無視するかもしれない.
しかしながら、Rangeは転送の部分的な失敗から効率的な復帰や巨大な表現の部分的な検索をサポートするため、オリジンserverや中間キャッシュは可能であればbyte範囲をサポートすべきである.
**serverはGET以外のリクエストメソッドを伴ったRangeヘッダフィールドを無視しなければならない**.

**オリジンserverは理解できないrange unitを含むRangeヘッダフィールドを無視しなければならない**.
プロキシは理解できないrange unitを含むRangeヘッダフィールドを破棄するかもしれない.

Range requestsをサポートするserverは2つ以上の重複する範囲からなるRangeヘッダフィールドを無視するかもしれないし、または、昇順に並んでいない多くの小さな範囲集合を無視するかもしれない、それは両者は壊れたclientであるかもしくは意図的なDoS攻撃(Section 6.1)である事を示すからである.
**clientは同じデータを包含する単一の範囲よりも本質的に処理・転送効率の悪い複数範囲リクエストを行うべきではない**.

**複数範囲をリクエストしているclientは、後の部分を早急にリクエストする必要がある特定の場合を除き、それらの範囲を昇順に並べるべきである**(典型的には完全な表現として受け取られる順序である).
例えば、特に、もしその表現が逆の順序で格納されたページから構成されており、且つ、そのユーザーエージェント1度に1ページ転送する事を望むのであれば、パーツの内部カタログを持つ巨大な表現を処理しているユーザーエージェントは後半のパーツを初めにリクエストする必要があるかもしれない.

Rangeヘッダフィールドは https://tools.ietf.org/html/rfc7232[RFC7232] にて定義されている前提条件ヘッダフィールドを評価した後、且つ、Rangeヘッダフィールドが存在しない場合の結果が200(OK)レスポンスであるような場合にのみ評価される.
言い換えると、Rangeは条件付きGETが304(Not Modified)レスポンスを返す時に無視される.

`If-Range` ヘッダフィールド(Section 3.2)はRangeヘッダフィールドを適用するための前提条件として用いられ得る.

もし全ての前提条件が真であり、対象資源に対してserverがRangeヘッダフィールドをサポートしており、指定された範囲が(Section 2.1で定義されている通り)有効且つ充足可能であるならば、その**serverはSection 4で定義されている通り、充足可能なリクエストされた範囲に対応する1つ以上の部分的な表現を含んでいるペイロードをレスポンスとして持つ206(Partial Content)ステータスコードを送信するべきである**.

もしすべての前提条件が真であり、対象資源に対してserverがRangeヘッダフィールドをサポートしており、且つ、**指定された範囲が無効であるもしくは充足不可能である場合、serverは416(Range Not Satisfiable)レスポンスを返却すべきである**.

=== If-Range

もしあるclientが表現の部分的なコピーを持っており、且つ、表現全体の最新のコピーを持ちたいと望むのであれば、それは(`If-Unmodified-Since` と `If-Match` のどちらか一方、もしくは両方を使う)条件付きGETを用いたRangeヘッダフィールドを使う事ができるだろう.
しかしながら、もし表現が更新された事により前提条件が失敗した場合、clientは次に現在の表現全体を獲得するための第二のリクエストを作成する必要があるだろう.

`If-Range` ヘッダフィールドはclientが第二のリクエストを「短絡」させる事を可能にする.
非公式的に、その意味は次のようになる: もし表現が変更されていない場合、自分がRangeで指定している部分を自分に送信せよ; それ以外の場合、自分に表現全体を送信せよ.

```
  If-Range = entity-tag / HTTP-data
```

**clientはRangeヘッダフィールドを含まないリクエスト内にIf-Rangeヘッダフィールドを生成してはならない**.
**serverはRangeヘッダフィールドを含まないリクエスト内のIf-Rangeヘッダフィールドを無視しなければならない**.
**オリジンserverは受信したRange requestをサポートしていない対象資源に対するリクエスト内のIf-Rangeヘッダフィールドを無視しなければならない**.

**clientは弱い比較演算子としてマークされたETagを含むIf-Rangeヘッダフィールドを生成してはならない**.
**clientは表現に対応するETagを持たず、且つ、日付が https://tools.ietf.org/html/rfc7232#section-2.2.2[Section 2.2.2 of [RFC7232]] にて定義された意味で強い検証器である場合ではないようなHTTP-dateを含んでいるIf-Rangeヘッダフィールドを生成してはならない**.
**(要はIf-Rangeをclientが利用するにあたり、強い比較演算子を持つETag、または、強い検証器を持つHTTP-dataをIf-Rangeに含ませなければならないという事である)**

最初から括弧内に示した内容で書いてほしいとも思う(unlessは意味を把握する際に混乱が生じかねない)

事前条件If-Rangeを評価するserverは、**ETagの比較を行う時に強い比較関数を使わなければならない**、且つ、もし上述した**強い検証器ではないHTTP-data検証器が提供された場合は条件を偽として評価しなければならない**.

二重引用符間の最初の2文字を調べることによって、有効なETagは有効なHTTP-dataと区別する事ができる.

もしIf-Rangeヘッダフィールド内で与えれた検証器が対象資源の選択された表現に対する検証器と一致する場合、次に**serverは要求通りRangeヘッダフィールドを処理すべき**である.
**もし検証器が一致しない場合、serverはRangeヘッダフィールドを無視しなければならない**.
検証器がHTTP-dataである時も含んでいる完全一致によるこの比較はIf-Unmodified-Since条件を評価する際に用いられる `同時刻もしくはそれ以前` を比較するものとは異なる点に注意する事.

== Responses to a Range Request

=== 206 Partial Content
